version: "3.9"
services:
  paneles:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development